apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-asg-roller.fullname" . }}
  labels:
    {{- include "aws-asg-roller.labels" . | nindent 4 }}
  {{- with .Values.rbacAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
